apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: e2e-jenkins-deplymnt
spec:
  selector:
    matchLabels:
      app: e2ejenkins
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: e2ejenkins
    spec:
      containers:
        - name: e2ejenkins-k8s
          image: siva2428/e2ejenkins # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8006 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: e2ejenkins-svc
spec:
  selector:
    app: e2ejenkins
  ports:
    - protocol: "TCP"
      port: 8006 # The port that the service is running on in the cluster
      targetPort: 8006 # The port exposed by the service
  type: NodePort # type of the service.